In [1]:
#Importing libraries

In [2]:
from keras.models import Sequential 

In [3]:
from keras.layers import Conv2D, MaxPooling2D, BatchNormalization 

In [4]:
from keras.layers import Activation, Dropout, Flatten, Dense

In [5]:
import os
import cv2
from PIL import Image
import numpy as np


In [6]:
#data collection

In [7]:
import cv2

classes = {'fresh_tomato':0,'stale_tomato':1}
x=[]
y=[]
for cls in classes:
    pth='D://Tomatoes//'+cls
    for j in os.listdir(pth):
        img=cv2.imread(os.path.join(pth,j),0)
        img=cv2.resize(img,(200,200))
        x.append(img)
        y.append(classes[cls])

In [8]:
print(classes)

{'fresh_tomato': 0, 'stale_tomato': 1}


In [9]:
y = np.array(y)
x = np.array(x)

In [10]:
print(x[10])

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [11]:
#data splitting

In [12]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.20, random_state = 0, stratify = y)



In [13]:
#data normalization

In [14]:
X_train = X_train / 255.0
X_test = X_test / 255.0


In [15]:
#building neural network

In [16]:
INPUT_SHAPE = (200, 200, 1)   

model = Sequential()
model.add(Conv2D(32, (3, 3), input_shape=INPUT_SHAPE))
          
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(32, (3, 3), kernel_initializer = 'he_uniform'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(64, (3, 3), kernel_initializer = 'he_uniform'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Flatten())
model.add(Dense(64))
model.add(Activation('relu'))
model.add(Dropout(0.5))

model.add(Dense(1))
model.add(Activation('sigmoid'))  

model.compile(loss='binary_crossentropy',
              optimizer='rmsprop',            
              metrics=['accuracy'])

In [17]:
print(model.summary())  

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 198, 198, 32)      320       
                                                                 
 activation (Activation)     (None, 198, 198, 32)      0         
                                                                 
 max_pooling2d (MaxPooling2  (None, 99, 99, 32)        0         
 D)                                                              
                                                                 
 conv2d_1 (Conv2D)           (None, 97, 97, 32)        9248      
                                                                 
 activation_1 (Activation)   (None, 97, 97, 32)        0         
                                                                 
 max_pooling2d_1 (MaxPoolin  (None, 48, 48, 32)        0         
 g2D)                                                   

In [18]:
#model training

In [19]:
model.fit(X_train, y_train, epochs=60, batch_size=32, validation_split=0.2)

Epoch 1/60


40/40 [==============================] - 12s 277ms/step - loss: 1.1002 - accuracy: 0.4944 - val_loss: 0.6932 - val_accuracy: 0.4936
Epoch 2/60
40/40 [==============================] - 11s 264ms/step - loss: 0.7042 - accuracy: 0.4960 - val_loss: 0.6934 - val_accuracy: 0.4522
Epoch 3/60
40/40 [==============================] - 10s 259ms/step - loss: 0.6950 - accuracy: 0.5151 - val_loss: 0.7603 - val_accuracy: 0.4936
Epoch 4/60
40/40 [==============================] - 10s 262ms/step - loss: 0.6979 - accuracy: 0.5326 - val_loss: 0.6839 - val_accuracy: 0.4936
Epoch 5/60
40/40 [==============================] - 10s 259ms/step - loss: 0.6759 - accuracy: 0.5725 - val_loss: 0.6748 - val_accuracy: 0.5892
Epoch 6/60
40/40 [==============================] - 10s 261ms/step - loss: 0.6584 - accuracy: 0.6330 - val_loss: 0.7122 - val_accuracy: 0.5637
Epoch 7/60
40/40 [==============================] - 10s 263ms/step - loss: 0.5944 - accuracy: 0.6664 - val_loss: 0.5935 - val_accuracy: 0.67

40/40 [==============================] - 12s 300ms/step - loss: 0.1113 - accuracy: 0.9498 - val_loss: 0.1664 - val_accuracy: 0.9268
Epoch 55/60
40/40 [==============================] - 12s 308ms/step - loss: 0.1068 - accuracy: 0.9419 - val_loss: 0.2063 - val_accuracy: 0.8949
Epoch 56/60
40/40 [==============================] - 12s 296ms/step - loss: 0.0887 - accuracy: 0.9562 - val_loss: 0.4083 - val_accuracy: 0.8694
Epoch 57/60
40/40 [==============================] - 12s 297ms/step - loss: 0.1020 - accuracy: 0.9506 - val_loss: 0.1727 - val_accuracy: 0.9108
Epoch 58/60
40/40 [==============================] - 12s 298ms/step - loss: 0.1203 - accuracy: 0.9395 - val_loss: 0.1653 - val_accuracy: 0.9299
Epoch 59/60
40/40 [==============================] - 12s 305ms/step - loss: 0.0773 - accuracy: 0.9554 - val_loss: 0.1749 - val_accuracy: 0.9172
Epoch 60/60
40/40 [==============================] - 13s 316ms/step - loss: 0.1319 - accuracy: 0.9427 - val_loss: 0.1730 - val_accuracy: 0.9236


In [20]:
os.getcwd()

'C:\\Users\\Khushali Gupta\\Downloads'

In [37]:
#model prediction

import cv2
image_path = "D:/Tomatoes/fresh_tomato/DSCN4069.jpg_0_76.jpg"
image = cv2.imread(image_path)
image = cv2.resize(image,(200,200))
image = image.reshape(3,200,200,1) / 255.0
q=model.predict(image)
print(q)
if(q[0]>0.5):
    print("Poor Quality")
else:
    print("Good Quality")

1/1 [==============================] - 0s 33ms/step
[[4.3812044e-26]
 [1.0000000e+00]
 [5.5102859e-28]]
Good Quality
